<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_BA_H" Id="{9203f046-b779-4ce2-8aaf-409d090a62f4}" SpecialFunc="None">
    <Declaration><![CDATA[{region '#Template'}
	{attribute 'Version' := '0.0.1.0'}
	{attribute 'Tags' := '"LCID": "1031", "Text": "Trade, Plant, Heating System"'}
	{attribute 'Tags' := '"LCID": "1033", "Text": "Trade, Plant, Heating System"'}
	{attribute 'Description' := '"LCID": "1031", "Text": "Aufruf der Anlagen des Gewerks Heizsysteme"'}
	{attribute 'Description' := '"LCID": "1033", "Text": "Calling the plants of the trade heating system"'}
{endregion}
FUNCTION_BLOCK FB_BA_H EXTENDS FB_BA_View
VAR_INPUT CONSTANT
	HTC01				: FB_BA_H_HtgCir01;		
END_VAR
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <CFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCImplementationObject">
              <o n="Items" t="CFCItemList">
                <l2 n="InnerList" cet="CFCBoxElement">
                  <o>
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_View"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">23L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"SUPER^"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">24L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eNodeType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"eOrganizational"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">16</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BACnetNodeType"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">25L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">26L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">27L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"udiObjectInstance"</v>
                          <n n="Value" />
                          <v n="InitialValue">"16#3FFFFF"</v>
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">28L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"Device"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BACnetGlobals.BACnetIpStandardDevice"</v>
                          <o n="Type" t="ReferenceType">
                            <n n="BaseType" />
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">29L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"1, 1, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">22L</v>
                  </o>
                  <o>
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCInputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">48L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">49L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">50L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">51L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">52L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">53L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">54L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">55L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">56L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bDst"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">57L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bTWthCrit"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">58L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fTWthDamped"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">59L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fSpFrstProtec"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">60L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"eOpMod"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">61L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bRls"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">62L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fSp"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">63L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bPu"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">64L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fVlv"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">65L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_H_HtgCir01"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">66L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"HTC01"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">67L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"TFlCtrl"</v>
                          <n n="Value" />
                          <v n="InitialValue">"STRUCT(iParent := THIS^, iLabel := LabelAggregates.FlowTemperatureControl, sObjectName := '[Idx=01]', Ctrl := STRUCT(eOutputUnit := E_BA_Unit.eOther_Percent, eActionRm := E_BA_Action.eReverse, fMinOutputRm := 0, fMaxOutputRm := 100, fProportionalConstant := 3, fIntegralConstant := 180))"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">9</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_PID"</v>
                            </o>
                            <v n="SignatureId">6088</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">68L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"HtgLmt"</v>
                          <n n="Value" />
                          <v n="InitialValue">"STRUCT(iParent := THIS^, iLabel := LabelAggregates.HeatingLimit, sObjectName := '[Idx=01]', eDPADMode := E_BA_DPADMode.eInclude)"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">12</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_HtgLmt"</v>
                            </o>
                            <v n="SignatureId">5675</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">69L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"OpMod"</v>
                          <n n="Value" />
                          <v n="InitialValue">"STRUCT(iParent := THIS^, iLabel := LabelAggregates.OperationMode, sObjectName := '[Idx=01]', eDPADMode := E_BA_DPADMode.eInclude)"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_H_OpMod"</v>
                            </o>
                            <v n="SignatureId">5698</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">70L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"Sp"</v>
                          <n n="Value" />
                          <v n="InitialValue">"STRUCT(iParent := THIS^, iLabel := LabelAggregates.SetpointGeneration, sObjectName := '[Idx=01]', eDPADMode := E_BA_DPADMode.eInclude)"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">17</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_H_HtgCir_Sp"</v>
                            </o>
                            <v n="SignatureId">5720</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">71L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"Pu"</v>
                          <n n="Value" />
                          <v n="InitialValue">"STRUCT(iParent := THIS^, iLabel := LabelAggregates.Pump, sObjectName := '[Idx=01]', eDPADMode := E_BA_DPADMode.eInclude)"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_Pu1st"</v>
                            </o>
                            <v n="SignatureId">6304</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">72L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"Vlv"</v>
                          <n n="Value" />
                          <v n="InitialValue">"STRUCT(iParent := THIS^, iLabel := LabelAggregates.Valve, sObjectName := '[Idx=01]', eDPADMode := E_BA_DPADMode.eInclude)"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">9</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_Vlv"</v>
                            </o>
                            <v n="SignatureId">4211</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">73L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"TRt"</v>
                          <n n="Value" />
                          <v n="InitialValue">"STRUCT(iParent := THIS^, iLabel := LabelAggregates.TemperatureReturnFlow, sObjectName := '[Idx=01]', MV := STRUCT(eUnit := E_BA_Unit.eTemperature_DegreesCelsius, eEnPlantLock := E_BA_LockPriority.eNoLock, fResolution := 0.01, fScaleOffset := 0))"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">18</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog"</v>
                            </o>
                            <v n="SignatureId">4129</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">74L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"TFl"</v>
                          <n n="Value" />
                          <v n="InitialValue">"STRUCT(iParent := THIS^, iLabel := LabelAggregates.TemperatureFlow, sObjectName := '[Idx=01]', MV := STRUCT(eUnit := E_BA_Unit.eTemperature_DegreesCelsius, eEnPlantLock := E_BA_LockPriority.eMedium, fResolution := 0.01, fScaleOffset := 0))"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">18</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog"</v>
                            </o>
                            <v n="SignatureId">4129</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">75L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bRebuildSegments"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">76L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bAcknowledgeRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">77L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eNodeType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_NodeType.Automatic"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_NodeType"</v>
                            </o>
                            <v n="SignatureId">1058</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">78L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">7450</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">79L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">7450</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">80L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eAssignAsTrendRef"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_AssignRefMode.eInitByProfile"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">18</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_AssignRefMode"</v>
                            </o>
                            <v n="SignatureId">1054</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">81L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDeviceType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="StringType">
                            <n n="SizeExpression" />
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">82L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nInstanceID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">83L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEnShare"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">84L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"11, 7, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">47L</v>
                  </o>
                </l2>
              </o>
              <o n="ParameterInitializationMethodGenerator" t="CFCParameterInitializationMethodObject">
                <v n="GuidPOU">{f5a6fde4-414b-4719-9496-4d5e8e50d7f3}</v>
                <v n="GuidParentObject">{9203f046-b779-4ce2-8aaf-409d090a62f4}</v>
                <v n="MethodName">"__InitializeParameters_FB_BA_H"</v>
                <v n="ReturnType">"BOOL"</v>
              </o>
              <o n="RoutingPathTable" t="CFCRoutingPathTable">
                <d2 n="InnerDictionary" />
              </o>
              <v n="AutoSizeCanvas">true</v>
              <v n="CanvasWidth">25</v>
              <v n="CanvasHeight">17</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolType">{fd373d9e-533d-4d69-ad04-82ccf513ff10}</Type>
            <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
            <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
            <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
            <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
            <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
            <Type n="CFCParameter">{16471219-97ce-4580-8682-e60492a6d970}</Type>
            <Type n="CFCParameterInitializationMethodObject">{f13d20a6-591c-4ca8-9a3d-8574380b6bcc}</Type>
            <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
            <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
            <Type n="CompilerMessage">{bc2be951-49f6-4f0f-b731-e31e36606f1e}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int16">System.Int16</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
            <Type n="ParameterOrigin">{00f7522c-f616-4f07-a530-7175f7cba90b}</Type>
            <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
            <Type n="ReferenceType">{861aad71-b796-49c8-8e44-0d476c5ed1ab}</Type>
            <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
            <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringType">{ab09737e-b891-4fc6-9c8c-246eb8cdb046}</Type>
            <Type n="UDIntType">{223d196a-c1d7-4283-aea6-270599207584}</Type>
            <Type n="UserdefType">{8499b87a-2b75-4c62-8657-e4aa9316c18b}</Type>
            <Type n="VariableExpression">{6708bd14-cddc-4e28-b69d-d3183b7c423e}</Type>
          </TypeList>
        </XmlArchive>
      </CFC>
    </Implementation>
    <Method Name="FB_init" Id="{aa91cbcf-a991-41d7-bcac-620d9975e82e}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[HTC01.iParent 					:= THIS^;	
HTC01.sObjectName				:= CONCAT(TxTPlant_Heating_circuit_sObjectName,'01');							
HTC01.sDescription				:= TxTPlant_Heating_circuit_sDescription;	
HTC01.eDPADMode					:= E_BA_DPADMode.eInclude;

HTC01.GeneralSettings.Subject	:= Site.GeneralSettings_Subject;
HTC01.GeneralSettings.sTarget	:= Site.GeneralSettings_NetId;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_BA_H.FB_init">
      <LineId Id="39" Count="5" />
      <LineId Id="33" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>