<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_BA_AirConditioning" Id="{bdc7bc27-4147-48f1-9968-568ce857494b}" SpecialFunc="None">
    <Declaration><![CDATA[{region '#Template'}
	{attribute 'Version' := '5.0.0.0'}
	{attribute 'Tags' := '"LCID": "1031", "Text": "Trade, Plant, AC"'}
	{attribute 'Tags' := '"LCID": "1033", "Text": "Trade, Plant, AC"'}
	{attribute 'Using' := '"Type": "Template", "URI": "Site"'}
	{attribute 'Description' := '"LCID": "1031", "Text": "Aufruf der Anlagen des Gewerks Klimaanlagen"'}
	{attribute 'Description' := '"LCID": "1033", "Text": "Calling the plants of the trade air conditioning"'}
{endregion}
FUNCTION_BLOCK FB_BA_AirConditioning EXTENDS FB_BA_View
VAR_INPUT CONSTANT
	AHU01				: FB_BA_AHU_1st_10;
END_VAR
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <CFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCImplementationObject">
              <o n="Items" t="CFCItemList">
                <l2 n="InnerList" cet="CFCBoxElement">
                  <o>
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_View"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">10L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"SUPER^"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">11L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bAcknowledgeRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">321L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eNodeType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_NodeType.Automatic"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_NodeType"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">322L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sTag"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="StringType">
                            <n n="SizeExpression" />
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">323L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">324L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">325L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eAssignAsTrendRef"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_AssignRefMode.eInitByProfile"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">18</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_AssignRefMode"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">326L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDeviceType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">16</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_BA_SmallString"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">327L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nInstanceID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">328L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEnPublish"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">329L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"2, 1, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">9L</v>
                  </o>
                  <o>
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_AHU_1st_10"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">35L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"AHU01"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">36L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"stTSeqLink"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"ST_BA_SeqLink"</v>
                            </o>
                            <v n="SignatureId">3760</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">408L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"TSeqLink"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_AC_SeqT"</v>
                            </o>
                            <v n="SignatureId">9086</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">409L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"PlantCmd"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">28</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_AC_PlantCmd_AHU_1st_10"</v>
                            </o>
                            <v n="SignatureId">9089</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">410L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"PlantLock"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">15</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_PlantLock"</v>
                            </o>
                            <v n="SignatureId">8469</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">411L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"OpMod"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_AC_OpMod1St_Prio"</v>
                            </o>
                            <v n="SignatureId">9103</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">412L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"SumNgtCol"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">18</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_AC_SumNgtCol"</v>
                            </o>
                            <v n="SignatureId">9106</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">413L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"TCasCtrl"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">20</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_AC_TCasCtrl_01"</v>
                            </o>
                            <v n="SignatureId">9109</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">414L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"SpTRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">19</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_Scale_04_Y2_3"</v>
                            </o>
                            <v n="SignatureId">9112</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">415L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"Col"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">16</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_AC_ColT_02"</v>
                            </o>
                            <v n="SignatureId">9115</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">416L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"Erc"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">17</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_AC_ErcPl_02"</v>
                            </o>
                            <v n="SignatureId">9130</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">417L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"PreHtr"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">15</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_AC_PreHtr"</v>
                            </o>
                            <v n="SignatureId">9142</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">418L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"ExtADiffPrssMonit"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">15</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_FdbAnalog"</v>
                            </o>
                            <v n="SignatureId">9166</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">419L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"ExtAFan"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">15</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_MotCtlExt"</v>
                            </o>
                            <v n="SignatureId">9169</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">420L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"ExtADiffPrss"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">421L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"ExtAPrss"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">422L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"ExhADmp"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_Dmp2P"</v>
                            </o>
                            <v n="SignatureId">9175</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">423L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"SuADiffPrssMonit"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">15</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_FdbAnalog"</v>
                            </o>
                            <v n="SignatureId">9166</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">424L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"SuAFan"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">15</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_MotCtlExt"</v>
                            </o>
                            <v n="SignatureId">9169</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">425L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"SuADiffPrss"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">426L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"SuAPrss"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">427L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"OuADmp"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_Dmp2P"</v>
                            </o>
                            <v n="SignatureId">9175</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">428L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"FiltExtAMonit"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">12</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_Hys_21"</v>
                            </o>
                            <v n="SignatureId">9181</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">429L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"DiffPrssExtAFilt"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">430L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"FiltOuAMonit"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">12</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_Hys_21"</v>
                            </o>
                            <v n="SignatureId">9181</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">431L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"DiffPrssOuAFilt"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">432L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"TRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">433L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"TExtA"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">434L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"TSuA"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">435L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"TExhA"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">436L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"TOuA"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">22</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_SensorAnalog_Raw"</v>
                            </o>
                            <v n="SignatureId">9127</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">437L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bAcknowledgeRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">438L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eNodeType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_NodeType.Automatic"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_NodeType"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">439L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sTag"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="StringType">
                            <n n="SizeExpression" />
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">440L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">441L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">442L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eAssignAsTrendRef"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_AssignRefMode.eInitByProfile"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">18</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_AssignRefMode"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">443L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDeviceType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">16</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_BA_SmallString"</v>
                            </o>
                            <v n="SignatureId">-1</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">444L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nInstanceID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">445L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEnPublish"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">446L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"10, 5, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">34L</v>
                  </o>
                </l2>
              </o>
              <o n="ParameterInitializationMethodGenerator" t="CFCParameterInitializationMethodObject">
                <v n="GuidPOU">{9629a5d3-2323-4b7c-ab56-886ffc380f2f}</v>
                <v n="GuidParentObject">{bdc7bc27-4147-48f1-9968-568ce857494b}</v>
                <v n="MethodName">"__InitializeParameters_FB_BA_AirConditioning"</v>
                <v n="ReturnType">"BOOL"</v>
              </o>
              <o n="RoutingPathTable" t="CFCRoutingPathTable">
                <d2 n="InnerDictionary" />
              </o>
              <v n="AutoSizeCanvas">true</v>
              <v n="CanvasWidth">22</v>
              <v n="CanvasHeight">11</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolType">{fd373d9e-533d-4d69-ad04-82ccf513ff10}</Type>
            <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
            <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
            <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
            <Type n="CFCParameter">{16471219-97ce-4580-8682-e60492a6d970}</Type>
            <Type n="CFCParameterInitializationMethodObject">{f13d20a6-591c-4ca8-9a3d-8574380b6bcc}</Type>
            <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
            <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
            <Type n="CompilerMessage">{bc2be951-49f6-4f0f-b731-e31e36606f1e}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int16">System.Int16</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
            <Type n="ParameterOrigin">{00f7522c-f616-4f07-a530-7175f7cba90b}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringType">{ab09737e-b891-4fc6-9c8c-246eb8cdb046}</Type>
            <Type n="UDIntType">{223d196a-c1d7-4283-aea6-270599207584}</Type>
            <Type n="UserdefType">{8499b87a-2b75-4c62-8657-e4aa9316c18b}</Type>
            <Type n="VariableExpression">{6708bd14-cddc-4e28-b69d-d3183b7c423e}</Type>
          </TypeList>
        </XmlArchive>
      </CFC>
    </Implementation>
    <Method Name="FB_init" Id="{0439e4e3-25f8-4f0e-a8ed-d1c0ce404fd0}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[AHU01.iParent 					:= THIS^;	                               
AHU01.iLabel					:= LblPlt_Partial_air_conditioning_system;	
AHU01.sObjectName				:= '{Idx=01}';                       
AHU01.eDPADMode					:= E_BA_DPADMode.eInclude;              
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_BA_AirConditioning.FB_init">
      <LineId Id="77" Count="0" />
      <LineId Id="108" Count="0" />
      <LineId Id="107" Count="0" />
      <LineId Id="80" Count="0" />
      <LineId Id="99" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>