<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN_OPTEXT_BACnet" Id="{52a9e81f-077d-4269-9264-70296922bd30}" SpecialFunc="None">
    <Declaration><![CDATA[// Optional extensions.
// [Hint]
// - To stay maintainable and sustain a nice project overview it is recommended to declare these tools in your MAIN program.
PROGRAM MAIN_OPTEXT_BACnet
VAR
	{region 'Settings'}
		// Intention:		Generically subscribe to certain events.
		//					> Use carefully (Refer to documentation - event subscribers are powerfull!)
		Events_LocObj		: FB_BACnet_MyLocalObjectEvents;
	{endregion}
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN_OPTEXT_BACnet">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>