resources:
 repositories:
   - repository: BuildTemplates
     type: git
     name: 'Common/BuildTemplates'
   - repository: BaBuildTemplates
     type: git
     name: 'BuildTemplates'

trigger: none

#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Variables
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
variables:

- name: isReleaseBranch
  value: ${{ or( eq(variables['Build.SourceBranch'],'refs/heads/master'), eq(variables['Build.SourceBranch'],'refs/heads/main') ) }}
- template: GlobalVars.yml

- template: Setup/VersionVars.yml@BuildTemplates
  parameters:
    VersionMajor: ${{variables.Major}}
    VersionMinor: ${{variables.Minor}}
    isReleaseBranch: ${{variables.isReleaseBranch}}

- name: 'ArchivesFolder'
  value: 'archives'

stages:
- stage: Build
  jobs:
          
  - job: Build
    pool:
      name: TwinCAT-Builds
      demands:
        - MD_VS_BUILD_TOOLS_2019
        - MD_SMALL
    steps:

    - template: InitBaBT.yml@BaBuildTemplates
    - template: SetPipelineName.yml@BaBuildTemplates
      parameters:
        name: $(Version.MajorMinorPatchPreReleaseNumber)
    
    #------------------------------------------------------------------------------------
    # Overview
    #------------------------------------------------------------------------------------
    - powershell: |
        echo "Samples version: $(Version.MajorMinorPatchPreReleaseNumber)"
        echo "From branch: $(Build.SourceBranchName)"
      displayName: 'Overview'

    #------------------------------------------------------------------------------------
    # Pull repository
    #------------------------------------------------------------------------------------
    - checkout: self
      path: 's'
      lfs: false
      clean: true
      persistCredentials: true
      displayName: 'Pull repository'

    #------------------------------------------------------------------------------------
    # Create Concept Samples
    #------------------------------------------------------------------------------------
    - template: CreateSampleArchive.yml
      parameters:
        sampleName: Concepts
        archivesFolder: $(ArchivesFolder)

    #------------------------------------------------------------------------------------
    # Create Template Samples
    #------------------------------------------------------------------------------------
    - template: CreateSampleArchive.yml
      parameters:
        sampleName: Templates
        archivesFolder: $(ArchivesFolder)
        
    #------------------------------------------------------------------------------------
    # Archive all archives
    #------------------------------------------------------------------------------------
    - task: ArchiveFiles@2
      displayName: Archive all archives
      inputs:
        rootFolderOrFile: ./$(ArchivesFolder)
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/TF8040 Samples V$(Version.MajorMinorPatchPreReleaseNumber).zip
          
    #------------------------------------------------------------------------------------
    # Save all archives
    #------------------------------------------------------------------------------------
    - task: PublishBuildArtifacts@1
      displayName: Save all archives
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: Samples

- stage: Release
  dependsOn: Build
  condition: and(succeeded(), and( eq( variables.isReleaseBranch, true ), or( eq( variables['Build.Reason'], 'IndividualCI' ), eq( variables['Build.Reason'], 'Manual' ) ) ) )
  variables:
    branchName: $[replace(variables['Build.SourceBranch'],'refs/heads/','')]
  displayName: Release
  jobs:
  - deployment: Release
    environment: 'TF8040-Release-Samples'
    pool:
      name: TwinCAT-Builds
      demands: MD_SMALL
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none

          #------------------------------------------------------------------------------------
          # Retain pipeline run
          #------------------------------------------------------------------------------------          
          - template: RetainOnSuccess.yml@BaBuildTemplates

  - job: TagCommit
    dependsOn: Release
    displayName: Tag commit
    pool:
      name: TwinCAT-Builds
      demands: MD_SMALL
    steps:
          
    - powershell: |
        echo "Branch: $(Build.SourceBranch)"
        echo "Branch name: $(branchName)"
        echo "Used version: $(Version.MajorMinorPatchPreReleaseNumber)"
        echo "Git Commit ID: $(Build.SourceVersion)"
        echo "Source Directory: $(Build.SourcesDirectory)"
      displayName: 'Overview'

    - checkout: self
      clean: true
      persistCredentials: true      
      displayName: 'Pull repository'

    - template: AddNewGitTag.yml@BuildTemplates
      parameters:
        GitTag: TF8040_Samples/$(Version.MajorMinorPatchPreReleaseNumber)
        BranchName: $(branchName)

    - template: CreateChangelog.yml@BaBuildTemplates
      parameters:
        WikiPage: 'Changelogs/Samples'
        WikipageName: '$(Version.MajorMinorPatchPreReleaseNumber)_BA'        