resources:
 repositories:
   - repository: BuildTemplates
     type: git
     name: 'Common/BuildTemplates'

trigger: none

#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Parameters
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
parameters:

- name: createTag
  displayName: Create GIT tag
  type: boolean
  default: false

#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Variables
#------------------------------------------------------------------------------------------------------------------------------------------------------------------------
variables:

- template: GlobalVars.yml

- name: useSourceBranchName
  ${{ if eq( variables['Build.SourceBranch'], variables['BetaBranch'] ) }}:
    value: false
  ${{ if ne( variables['Build.SourceBranch'], variables['BetaBranch'] ) }}:
    value: true

- template: Setup/VersionVars.yml@BuildTemplates
  parameters:
    VersionMajor: ${{variables.Major}}
    VersionMinor: ${{variables.Minor}}
    VersionPatchDefault: ${{variables.Patch}}
    MainBranch: ${{variables.MainBranch}}
    UseSourceBranchName: ${{variables.useSourceBranchName}}
    AutoPatch: false
    PreReleaseName: ${{variables.PreReleaseName}})

- name: 'ArchivesFolder'
  value: 'archives'

jobs:
        
- job: CreateTF8040Samples
  pool:
    name: TwinCAT-Builds
    demands:
      - MD_VS_BUILD_TOOLS_2019
      - MD_SMALL
  steps:

  - template: Setup/VersionVarsValidateManualPatch.yml@BuildTemplates
    parameters:      
      MainBranch: ${{variables.MainBranch}}        
  - template: Setup/VersionVarsSetPipelineName.yml@BuildTemplates
  
  #------------------------------------------------------------------------------------
  # Overview
  #------------------------------------------------------------------------------------
  - powershell: |
      echo "Samples version: $(Version.NuGetVersion)"
      echo "From branch: $(Build.SourceBranchName)"
      
      [string]$runName = "$(Version.NuGetVersion)"

      if ('$(Build.Reason)' -eq 'Schedule') {
        $runName += "_Daily"
      } elseif ('$(Build.Reason)' -eq 'Manual') {
        $runName += "_Manual"
      } elseif ('$(Build.Reason)' -eq 'PullRequest') {
        $runName += "_PR"
      }

      Write-Output "##vso[build.updatebuildnumber]$runName"
    displayName: 'Overview'

  #------------------------------------------------------------------------------------
  # Pull repository
  #------------------------------------------------------------------------------------
  - checkout: self
    path: 's'
    lfs: false
    clean: true
    persistCredentials: true
    displayName: 'Pull repository'

  #------------------------------------------------------------------------------------
  # Create Concept Samples
  #------------------------------------------------------------------------------------
  - template: CreateSampleArchive.yml
    parameters:
      sampleName: Conecpt Samples
      version: $(Version.NuGetVersion)
      archivesFolder: $(ArchivesFolder)

  #------------------------------------------------------------------------------------
  # Create Template Samples
  #------------------------------------------------------------------------------------
  - template: CreateSampleArchive.yml
    parameters:
      sampleName: Template Samples
      version: $(Version.NuGetVersion)
      archivesFolder: $(ArchivesFolder)
      
  #------------------------------------------------------------------------------------
  # Archive all archives
  #------------------------------------------------------------------------------------
  - task: ArchiveFiles@2
    displayName: Archive all archives
    inputs:
      rootFolderOrFile: ./$(ArchivesFolder)
      includeRootFolder: false
      archiveType: zip
      archiveFile: $(Build.ArtifactStagingDirectory)/TF8040 Samples V1.$(Version.NuGetVersion).zip
        
  #------------------------------------------------------------------------------------
  # Save all archives
  #------------------------------------------------------------------------------------
  - task: PublishBuildArtifacts@1
    displayName: Save all archives
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: Samples      
      
  - ${{ if eq(parameters.createTag, 'true') }}:
    #------------------------------------------------------------------------------------
    # Add a tag to the commit
    #------------------------------------------------------------------------------------
    - template: AddNewGitTag.yml@BuildTemplates
      parameters:
        GitTag: $(Version.NuGetVersion)