<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_BA_SensorAnalog" Id="{cfcd59f3-625b-4240-9dbf-8c87dfb72373}" SpecialFunc="None">
    <Declaration><![CDATA[{region '#Template'}
	{attribute 'Version' := '5.1.0.0'}
	{attribute 'Tags' := '"LCID": "1031", "Text": "Universal, Sensor, AI"'}
	{attribute 'Tags' := '"LCID": "1033", "Text": "Universal, Sensor, AI"'}
	{attribute 'Using' := '"Type": "Template", "URI": "EC_ID"'}
	{attribute 'Using' := '"Type": "Template", "URI": "BA2_Param"'}
	{attribute 'Description' := '"LCID": "1031", "Text": "AI mit IO"'}
	{attribute 'Description' := '"LCID": "1033", "Text": "AI with IO"'}
{endregion}
FUNCTION_BLOCK FB_BA_SensorAnalog EXTENDS FB_BA_View
VAR_INPUT
END_VAR
VAR_INPUT CONSTANT
	MV						: FB_BA_AI_Raw;		
END_VAR
VAR_OUTPUT
	fPresentValue			: REAL;
	bEvent					: BOOL;
	eEventState				: E_BA_EventState;	
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <CFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCImplementationObject">
              <o n="Items" t="CFCItemList">
                <l2 n="InnerList">
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">228L</v>
                    <v n="DestPinId">272L</v>
                    <v n="Id">274L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">226L</v>
                    <v n="DestPinId">268L</v>
                    <v n="Id">270L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">98L</v>
                    <v n="DestPinId">79L</v>
                    <v n="Id">111L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_View"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">33L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"SUPER^"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">34L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bRebuildSegments"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">427L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bAcknowledgeRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">428L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eNodeType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_NodeType.Automatic"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_NodeType"</v>
                            </o>
                            <v n="SignatureId">1476</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">429L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sTag"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="StringType">
                            <n n="SizeExpression" />
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">430L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">4071</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">431L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">4071</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">432L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eAssignAsTrendRef"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_AssignRefMode.eInitByProfile"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">18</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_AssignRefMode"</v>
                            </o>
                            <v n="SignatureId">1472</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">433L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDeviceType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">16</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_BA_SmallString"</v>
                            </o>
                            <v n="SignatureId">3595</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">434L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nInstanceID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">435L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEnPublish"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">436L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"3, 1, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">32L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCInputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">569L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">571L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">226L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">228L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">98L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"nRawState"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">570L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"nRawVal"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">572L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bEvent"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">227L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"eEventState"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">229L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fPresentValue"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">99L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_AI_Raw"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">100L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"MV"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">101L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fScaleOffset"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Param.fInput_DefScaleOffset"</v>
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">649L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fResolution"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Param.fInput_DefResolution"</v>
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">650L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fLimitDeadband"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Param.fDefLimitDeadband"</v>
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">651L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"stHighLimit"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">16</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"ST_BA_LimitParam"</v>
                            </o>
                            <v n="SignatureId">3456</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">652L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"stLowLimit"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">16</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"ST_BA_LimitParam"</v>
                            </o>
                            <v n="SignatureId">3456</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">653L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fCOVIncrement"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Param.fDefCOVIncrement"</v>
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">654L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eUnit"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_Unit.Invalid"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">9</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_Unit"</v>
                            </o>
                            <v n="SignatureId">6801</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">655L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEnOutOfService"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">656L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eCommissioningState"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_CommissioningState.eUnknown"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">23</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_CommissioningState"</v>
                            </o>
                            <v n="SignatureId">1359</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">657L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sAddress"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">16</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_BA_SmallString"</v>
                            </o>
                            <v n="SignatureId">3508</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">658L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"stTimeDelay"</v>
                          <n n="Value" />
                          <v n="InitialValue">"F_BA_TimeDelay(XBA_Param.nDefTimeDelay_ToAbnormal, 0)"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">20</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"ST_BA_TimeDelayParam"</v>
                            </o>
                            <v n="SignatureId">3505</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">659L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eEnPlantLock"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_LockPriority.eNoLock"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">17</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_LockPriority"</v>
                            </o>
                            <v n="SignatureId">1364</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">660L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bAcknowledgeRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">661L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"aEventTransitionText"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Param.aEventTransitionText"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">24</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_BA_EventTransitionText"</v>
                            </o>
                            <v n="SignatureId">3371</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">662L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nEventClassID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">663L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"aEventEnable"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">21</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_BA_EventTransitions"</v>
                            </o>
                            <v n="SignatureId">3370</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">664L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEventDetectionEnable"</v>
                          <n n="Value" />
                          <v n="InitialValue">"TRUE"</v>
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">665L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sTag"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="StringType">
                            <n n="SizeExpression" />
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">666L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">3565</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">667L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">3565</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">668L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eAssignAsTrendRef"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_AssignRefMode.eInitByProfile"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">18</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_AssignRefMode"</v>
                            </o>
                            <v n="SignatureId">1366</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">669L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDeviceType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"XBA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">16</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_BA_SmallString"</v>
                            </o>
                            <v n="SignatureId">3508</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">670L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nInstanceID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">671L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEnPublish"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">672L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"12, 7, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">97L</v>
                  </o>
                  <o t="CFCOutputElement">
                    <o n="Input" t="CFCInputPinWithSetReset">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="ProcessValue">""</v>
                      <v n="Access" t="ProcessValueAccess">None</v>
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">268L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bEvent"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">269L</v>
                    </o>
                    <v n="PageArea">4</v>
                    <v n="Bounds">"28, 9, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">267L</v>
                  </o>
                  <o t="CFCOutputElement">
                    <o n="Input" t="CFCInputPinWithSetReset">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="ProcessValue">""</v>
                      <v n="Access" t="ProcessValueAccess">None</v>
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">272L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"eEventState"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">273L</v>
                    </o>
                    <v n="PageArea">4</v>
                    <v n="Bounds">"28, 10, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">271L</v>
                  </o>
                  <o t="CFCOutputElement">
                    <o n="Input" t="CFCInputPinWithSetReset">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="ProcessValue">""</v>
                      <v n="Access" t="ProcessValueAccess">None</v>
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">79L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"fPresentValue"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">80L</v>
                    </o>
                    <v n="PageArea">4</v>
                    <v n="Bounds">"28, 11, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">78L</v>
                  </o>
                </l2>
              </o>
              <o n="ParameterInitializationMethodGenerator" t="CFCParameterInitializationMethodObject">
                <v n="GuidPOU">{8682b944-24e1-41e7-9a02-e9036fa77acc}</v>
                <v n="GuidParentObject">{cfcd59f3-625b-4240-9dbf-8c87dfb72373}</v>
                <v n="MethodName">"__InitializeParameters_FB_BA_SensorAnalog"</v>
                <v n="ReturnType">"BOOL"</v>
              </o>
              <o n="RoutingPathTable" t="CFCRoutingPathTable">
                <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                  <o>
                    <v n="ConnectionId">274L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">24</v>
                      <v n="Y">10</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">24</v>
                        <v n="Y">10</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">27</v>
                        <v n="Y">10</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">270L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">24</v>
                      <v n="Y">9</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">24</v>
                        <v n="Y">9</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">27</v>
                        <v n="Y">9</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">111L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">24</v>
                      <v n="Y">11</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">24</v>
                        <v n="Y">11</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">100</v>
                      </o>
                      <o>
                        <v n="X">27</v>
                        <v n="Y">11</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                </d2>
              </o>
              <v n="AutoSizeCanvas">true</v>
              <v n="CanvasWidth">37</v>
              <v n="CanvasHeight">15</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolType">{fd373d9e-533d-4d69-ad04-82ccf513ff10}</Type>
            <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
            <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
            <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
            <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
            <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
            <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
            <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
            <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
            <Type n="CFCParameter">{16471219-97ce-4580-8682-e60492a6d970}</Type>
            <Type n="CFCParameterInitializationMethodObject">{f13d20a6-591c-4ca8-9a3d-8574380b6bcc}</Type>
            <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
            <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
            <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
            <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
            <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
            <Type n="CompilerMessage">{bc2be951-49f6-4f0f-b731-e31e36606f1e}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int16">System.Int16</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
            <Type n="ParameterOrigin">{00f7522c-f616-4f07-a530-7175f7cba90b}</Type>
            <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
            <Type n="RealType">{4c33f62d-2ba9-4951-b27c-3cedc666c650}</Type>
            <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
            <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringType">{ab09737e-b891-4fc6-9c8c-246eb8cdb046}</Type>
            <Type n="UDIntType">{223d196a-c1d7-4283-aea6-270599207584}</Type>
            <Type n="UserdefType">{8499b87a-2b75-4c62-8657-e4aa9316c18b}</Type>
            <Type n="VariableExpression">{6708bd14-cddc-4e28-b69d-d3183b7c423e}</Type>
          </TypeList>
        </XmlArchive>
      </CFC>
    </Implementation>
    <Method Name="FB_init" Id="{a6e402cc-5aee-4b3c-9df2-e05903bbe2ed}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[MV.iParent						:= THIS^;		
MV.iLabel						:= LblFun_MeasuredValue; 
MV.eUnit						:= E_BA_Unit.eTemperature_DegreesCelsius;
MV.fResolution 					:= 0.01;
MV.fScaleOffset 				:= 0; 	
MV.fCOVIncrement				:= BA2_Param.fDefCOVIncrement;
MV.nEventClassID				:= EC_ID.NC30;
MV.stTimeDelay.nToNormal		:= BA2_Param.nDefTimeDelay_ToNormal;
MV.stTimeDelay.nToAbnormal		:= BA2_Param.nDefTimeDelay_ToAbnormal;
MV.stHighLimit.bEnable			:= FALSE;
MV.stHighLimit.fValue			:= 0.0;		
MV.stLowLimit.bEnable			:= FALSE;
MV.stLowLimit.fValue			:= 0.0;
MV.fLimitDeadband 				:= BA2_Param.fDefLimitDeadband;
MV.aEventTransitionText[1]		:= txtEvent_Exceeded;
MV.aEventTransitionText[2]		:= txtEvent_Disturb;
MV.aEventTransitionText[3]		:= txtEvent_Normal;
MV.bEventDetectionEnable		:= TRUE;
MV.eEnPlantLock					:= E_BA_LockPriority.eNoLock;	]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_BA_SensorAnalog.FB_init">
      <LineId Id="309" Count="17" />
      <LineId Id="307" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>