<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_BA_AC_ColTSuACtrl" Id="{d56d9680-4e9f-48b1-bbc5-a1bbcc1e6d0d}" SpecialFunc="None">
    <Declaration><![CDATA[{region '#Template'}
	{attribute 'Version' := '1.0.0.0'}
	{attribute 'Tags' := '"LCID": "1031", "Text": "AC, Aggregates, Cooler, Temperature, Controller"'}
	{attribute 'Tags' := '"LCID": "1033", "Text": "AC, Aggregates, Cooler, Temperature, Controller"'}
	{attribute 'Description' := '"LCID": "1031", "Text": "Kühler Zuluft Regler Temperatur"'}
	{attribute 'Description' := '"LCID": "1033", "Text": "Cooler Supply air controller temperature"'}
{endregion}
FUNCTION_BLOCK FB_BA_AC_ColTSuACtrl EXTENDS FB_BA_View
VAR_INPUT
	bEn						: BOOL;
	fSpTSuA					: REAL;// Sollwert Temperatur kühlen // Setpoint temperature cooling
	fTSuA					: REAL;// Zuluft Temperatur // Supply air temperature
	bSync					: BOOL;
	fSync					: REAL;
END_VAR
VAR_OUTPUT
	fY              		: REAL;
	bIsActive				: BOOL;	//	active sequence controller
	bOpState				: BOOL;	//	Release sequence link, sequence control is active	
END_VAR
VAR_INPUT CONSTANT
	Ctrl					: FB_BA_LoopSeq;
END_VAR]]></Declaration>
    <Implementation>
      <CFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCImplementationObject">
              <o n="Items" t="CFCItemList">
                <l2 n="InnerList">
                  <o t="CFCConnection">
                    <v n="Bounds">"4, 84, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">51L</v>
                    <v n="DestPinId">109L</v>
                    <v n="Id">170L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"4, 84, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">54L</v>
                    <v n="DestPinId">110L</v>
                    <v n="Id">169L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 7, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">117L</v>
                    <v n="DestPinId">148L</v>
                    <v n="Id">165L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">45L</v>
                    <v n="DestPinId">108L</v>
                    <v n="Id">190L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">186L</v>
                    <v n="DestPinId">116L</v>
                    <v n="Id">189L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">183L</v>
                    <v n="DestPinId">115L</v>
                    <v n="Id">188L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"-7, -28, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">195L</v>
                    <v n="DestPinId">198L</v>
                    <v n="Id">203L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"-7, -28, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">192L</v>
                    <v n="DestPinId">201L</v>
                    <v n="Id">204L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_View"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">172L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"SUPER^"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">173L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bAcknowledgeObjectsRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">174L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eNodeType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_NodeType.eGeneral"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_NodeType"</v>
                            </o>
                            <v n="SignatureId">662</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">175L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <v n="InitialValue">"CONCAT(BA_Globals.sCmdConcatTitle, BA_Globals.sWCDescription)"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">11050</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">176L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <v n="InitialValue">"CONCAT(BA_Globals.sCmdConcatTitle, BA_Globals.sWCObjectName)"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">11050</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">177L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nInstanceID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">178L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"3, 2, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">171L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">45L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bEn"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">46L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"5, 11, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">44L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">51L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"fSpTSuA"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">52L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"3, 12, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">50L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">54L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"fTSuA"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">55L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"4, 13, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">53L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">183L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bSync"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">184L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"4, 17, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">182L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">186L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"fSync"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">187L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"4, 18, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">185L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCInputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">108L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">109L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">110L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">111L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">112L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">113L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">115L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">116L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">117L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bEn"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">118L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fSetpoint"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">119L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fCtrlVal"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">120L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"eActionPgm"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">121L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fMinOutputPgm"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">122L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fMaxOutputPgm"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">123L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bEnSync"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">125L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fValSync"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">126L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"fPresentValue"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">127L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_LoopSeq"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">128L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"Ctrl"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">129L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"stStepDelay"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">20</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"ST_BA_StepDelayParam"</v>
                            </o>
                            <v n="SignatureId">4402</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">270L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nDampConstant"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">271L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fDerivativeConstant"</v>
                          <n n="Value" />
                          <v n="InitialValue">"0"</v>
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">272L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fIntegralConstant"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">273L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fProportionalConstant"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">274L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fMaxOutputRm"</v>
                          <n n="Value" />
                          <v n="InitialValue">"100"</v>
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">275L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fMinOutputRm"</v>
                          <n n="Value" />
                          <v n="InitialValue">"0"</v>
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">276L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fNeutralZone"</v>
                          <n n="Value" />
                          <v n="InitialValue">"0"</v>
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">277L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eActionRm"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_Action.eDirect"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_Action"</v>
                            </o>
                            <v n="SignatureId">871</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">278L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eOpMode"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Param.nLoop_DefOpMode"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">12</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_PIDMode"</v>
                            </o>
                            <v n="SignatureId">387</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">279L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"fCOVIncrement"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Param.fDefCOVIncrement"</v>
                          <o n="Type" t="RealType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">280L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eOutputUnit"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_Unit.eOther_Percent"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">9</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_Unit"</v>
                            </o>
                            <v n="SignatureId">713</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">281L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"iSynchronizedLoop"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">9</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"I_BA_LoopSeq"</v>
                            </o>
                            <v n="SignatureId">3159</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">282L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"iNextSequenceRef"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">9</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"I_BA_LoopSeq"</v>
                            </o>
                            <v n="SignatureId">3159</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">283L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <v n="InitialValue">"'[Descr]'"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">6769</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">284L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <v n="InitialValue">"'[ObjName]'"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">6769</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">285L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDeviceType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"'[DevType]'"</v>
                          <o n="Type" t="StringType">
                            <n n="SizeExpression" />
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">286L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nInstanceID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">287L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEnShare"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">288L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"12, 9, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">107L</v>
                  </o>
                  <o t="CFCOutputElement">
                    <o n="Input" t="CFCInputPinWithSetReset">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="ProcessValue">""</v>
                      <v n="Access" t="ProcessValueAccess">None</v>
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">148L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"fY"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">149L</v>
                    </o>
                    <v n="PageArea">4</v>
                    <v n="Bounds">"29, 11, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">147L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">195L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"Ctrl.OpState"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">196L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"9, 22, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">194L</v>
                  </o>
                  <o t="CFCOutputElement">
                    <o n="Input" t="CFCInputPinWithSetReset">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="ProcessValue">""</v>
                      <v n="Access" t="ProcessValueAccess">None</v>
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">198L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bOpState"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">199L</v>
                    </o>
                    <v n="PageArea">4</v>
                    <v n="Bounds">"21, 22, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">197L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">192L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"Ctrl.IsActive"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">193L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"9, 24, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">191L</v>
                  </o>
                  <o t="CFCOutputElement">
                    <o n="Input" t="CFCInputPinWithSetReset">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="ProcessValue">""</v>
                      <v n="Access" t="ProcessValueAccess">None</v>
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">201L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bIsActive"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">202L</v>
                    </o>
                    <v n="PageArea">4</v>
                    <v n="Bounds">"21, 24, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">200L</v>
                  </o>
                </l2>
              </o>
              <o n="ParameterInitializationMethodGenerator" t="CFCParameterInitializationMethodObject">
                <v n="GuidPOU">{d36e1739-bfc8-4fb9-879c-a3de05930c90}</v>
                <v n="GuidParentObject">{d56d9680-4e9f-48b1-bbc5-a1bbcc1e6d0d}</v>
                <v n="MethodName">"__InitializeParameters_FB_BA_AC_ColTSuACtrl"</v>
                <v n="ReturnType">"BOOL"</v>
              </o>
              <o n="RoutingPathTable" t="CFCRoutingPathTable">
                <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                  <o>
                    <v n="ConnectionId">204L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">16</v>
                      <v n="Y">24</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">16</v>
                        <v n="Y">24</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">20</v>
                        <v n="Y">24</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">203L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">16</v>
                      <v n="Y">22</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">16</v>
                        <v n="Y">22</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">20</v>
                        <v n="Y">22</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">188L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">9</v>
                      <v n="Y">17</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">9</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">11</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">190L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">9</v>
                      <v n="Y">11</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">9</v>
                        <v n="Y">11</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">11</v>
                        <v n="Y">11</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">189L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">9</v>
                      <v n="Y">18</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">9</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">11</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">169L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">9</v>
                      <v n="Y">13</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">9</v>
                        <v n="Y">13</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">11</v>
                        <v n="Y">13</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">170L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">9</v>
                      <v n="Y">12</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">9</v>
                        <v n="Y">12</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">11</v>
                        <v n="Y">12</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">165L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">25</v>
                      <v n="Y">11</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">25</v>
                        <v n="Y">11</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">28</v>
                        <v n="Y">11</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                </d2>
              </o>
              <v n="AutoSizeCanvas">true</v>
              <v n="CanvasWidth">34</v>
              <v n="CanvasHeight">27</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolType">{fd373d9e-533d-4d69-ad04-82ccf513ff10}</Type>
            <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
            <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
            <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
            <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
            <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
            <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
            <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
            <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
            <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
            <Type n="CFCParameter">{16471219-97ce-4580-8682-e60492a6d970}</Type>
            <Type n="CFCParameterInitializationMethodObject">{f13d20a6-591c-4ca8-9a3d-8574380b6bcc}</Type>
            <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
            <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
            <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
            <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
            <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
            <Type n="CompilerMessage">{bc2be951-49f6-4f0f-b731-e31e36606f1e}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int16">System.Int16</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
            <Type n="ParameterOrigin">{00f7522c-f616-4f07-a530-7175f7cba90b}</Type>
            <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
            <Type n="RealType">{4c33f62d-2ba9-4951-b27c-3cedc666c650}</Type>
            <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
            <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringType">{ab09737e-b891-4fc6-9c8c-246eb8cdb046}</Type>
            <Type n="UDIntType">{223d196a-c1d7-4283-aea6-270599207584}</Type>
            <Type n="UserdefType">{8499b87a-2b75-4c62-8657-e4aa9316c18b}</Type>
            <Type n="VariableExpression">{6708bd14-cddc-4e28-b69d-d3183b7c423e}</Type>
          </TypeList>
        </XmlArchive>
      </CFC>
    </Implementation>
    <Method Name="FB_init" Id="{d7d20e92-4553-4504-9685-492b4e0687c5}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Ctrl.iParent						:= THIS^;
Ctrl.iLabel							:= LblCmpAC.Cooler_TSuACtrl_Ctrl; 
Ctrl.sObjectName					:= '{Idx=01}';
Ctrl.eOpMode						:= BA2_Param.nLoop_DefOpMode;								 	 										 
Ctrl.eOutputUnit					:= E_BA_Unit.eOther_Percent;
Ctrl.eActionRm						:= E_BA_Action.eDirect;
Ctrl.fProportionalConstant			:= 3;
Ctrl.fIntegralConstant				:= 180;
Ctrl.fDerivativeConstant			:= 0;
Ctrl.fMaxOutputRm 					:= 100;
Ctrl.fMinOutputRm					:= 0;
Ctrl.fCOVIncrement					:= 0;
Ctrl.nDampConstant					:= 0;
Ctrl.fNeutralZone					:= 0;
]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_BA_AC_ColTSuACtrl.FB_init">
      <LineId Id="25" Count="13" />
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>