<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="FB_BA_ControlCabinetBasic" Id="{1161a53a-c10a-4cfa-be73-b8db629377b6}" SpecialFunc="None">
    <Declaration><![CDATA[{region '#Template'}
	{attribute 'Version' := '0.0.1.0'}
	{attribute 'Tags' := '"LCID": "1031", "Text": "General, Cabinet, Control cabinet, Acknowledgement"'}
	{attribute 'Tags' := '"LCID": "1033", "Text": "General, Cabinet, Control cabinet, Acknowledgement"'}
	{attribute 'Description' := '"LCID": "1031", "Text": "Schaltschrank Quittierung"'}
	{attribute 'Description' := '"LCID": "1033", "Text": "Control cabinet acknowledgement"'}
{endregion}
FUNCTION_BLOCK FB_BA_ControlCabinetBasic EXTENDS FB_BA_View
VAR
	// By default, the entire project structure can be acknowledged.
	// There may be constellations (e.g. multiple control cabinets) where only one part of the project structure (e.g. multiple buildings) has to be acknowledged.
	// > In this case separete parts can be assigned here: 
	iAckView1				: I_BA_View;
	iAckView2				: I_BA_View;
	iAckView3				: I_BA_View;
END_VAR
VAR_INPUT CONSTANT
	LampFault				: FB_BA_ActuatorCmd;		
	AckButton				: FB_BA_CombinationBI_BV;													
	RstHw					: FB_BA_ActuatorCmd;														
END_VAR
VAR				
	bIsDisturbed			: BOOL;
	bHasUnackEvent			: BOOL;
	bBlink					: BOOL;
	tAlmLampImpuls			: FB_BA_Blink;						
	tpResetHw				: TP;	
	rtrigRstSwi				: R_TRIG;
	bTrigRstSwi				: BOOL;
	rtrigRstButton			: R_TRIG;
	bTrigRstButton			: BOOL;	
END_VAR
]]></Declaration>
    <Implementation>
      <CFC>
        <XmlArchive>
          <Data>
            <o xml:space="preserve" t="CFCImplementationObject">
              <o n="Items" t="CFCItemList">
                <l2 n="InnerList">
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">3252L</v>
                    <v n="DestPinId">804L</v>
                    <v n="Id">3258L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">3255L</v>
                    <v n="DestPinId">805L</v>
                    <v n="Id">3257L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">3236L</v>
                    <v n="DestPinId">3246L</v>
                    <v n="Id">3250L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">3159L</v>
                    <v n="DestPinId">3235L</v>
                    <v n="Id">3248L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">659L</v>
                    <v n="DestPinId">1593L</v>
                    <v n="Id">1678L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">644L</v>
                    <v n="DestPinId">1592L</v>
                    <v n="Id">1677L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">776L</v>
                    <v n="DestPinId">984L</v>
                    <v n="Id">1007L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">1004L</v>
                    <v n="DestPinId">983L</v>
                    <v n="Id">1006L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"-8, -23, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">650L</v>
                    <v n="DestPinId">657L</v>
                    <v n="Id">694L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"-8, -23, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">653L</v>
                    <v n="DestPinId">658L</v>
                    <v n="Id">695L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"-8, -23, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">647L</v>
                    <v n="DestPinId">656L</v>
                    <v n="Id">696L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">806L</v>
                    <v n="DestPinId">772L</v>
                    <v n="Id">813L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">815L</v>
                    <v n="DestPinId">774L</v>
                    <v n="Id">817L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">3157L</v>
                    <v n="DestPinId">793L</v>
                    <v n="Id">3173L</v>
                  </o>
                  <o t="CFCConnection">
                    <v n="Bounds">"0, 0, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="SourcePinId">795L</v>
                    <v n="DestPinId">3230L</v>
                    <v n="Id">3232L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_View"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">10L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"SUPER^"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">11L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"3, 2, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">9L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"EventEvaluation"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">245L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">""</v>
                          <v n="Modifiable">false</v>
                          <v n="Id">246L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"3, 6, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">LocalAction</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">234L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">644L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bIsDisturbed"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">645L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"11, 17, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">643L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">647L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bHasUnackEvent"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">648L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"4, 20, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">646L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">650L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"TRUE"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">651L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"4, 21, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">649L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">653L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bBlink"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">654L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"4, 22, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">652L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCInputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">656L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">657L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">658L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">659L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">""</v>
                          <v n="Modifiable">false</v>
                          <v n="Id">660L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">""</v>
                          <v n="Modifiable">false</v>
                          <v n="Id">661L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">""</v>
                          <v n="Modifiable">false</v>
                          <v n="Id">662L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">""</v>
                          <v n="Modifiable">false</v>
                          <v n="Id">663L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"SEL"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">664L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">""</v>
                          <v n="Modifiable">false</v>
                          <v n="Id">665L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"14, 18, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">Operator</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">655L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCInputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">1586L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">1587L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">1588L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">1589L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">1592L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">1593L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">2478L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">2480L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">2482L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">2484L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">2486L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bEnSfty"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1598L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bValSfty"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1599L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bEnCrit"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1600L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bValCrit"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1601L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bEnPgm"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1604L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bValPgm"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1605L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bOpState"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">2479L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bActiveEn"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">2481L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"eActivePriority"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">2483L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bActiveVal"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">2485L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bCmd"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">2487L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_ActuatorCmd"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1610L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"LampFault"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1611L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"Cmd"</v>
                          <n n="Value" />
                          <v n="InitialValue">"STRUCT(iParent := THIS^, iLabel := LabelFunctions.SwitchingCommand, iProfile := Profiles.BEvt_DisExt_DisturbedNoneNormal_Command, sObjectName := '{Idx=01}', ePolarity := E_BA_Polarity.eNormal, eFeedbackPolarity := E_BA_Polarity.eNormal, eOverriddenPolarity := E_BA_Polarity.eNormal, bEventDetectionEnable := TRUE, eEnPlantLock := E_BA_LockPriority.eNoLock)"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_BO_IO"</v>
                            </o>
                            <v n="SignatureId">6396</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2488L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bRebuildSegments"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2489L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bAcknowledgeRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2490L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eNodeType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_NodeType.Automatic"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_NodeType"</v>
                            </o>
                            <v n="SignatureId">1282</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2491L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">3832</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2492L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">3832</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2493L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDeviceType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="StringType">
                            <n n="SizeExpression" />
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2494L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nInstanceID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2495L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEnShare"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2496L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"23, 11, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">1585L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">3157L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">3159L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bBI_PrVal"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">3158L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bBV_PrVal"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">3160L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_CombinationBI_BV"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1016L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"AckButton"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1017L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"Value"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_BV_Op"</v>
                            </o>
                            <v n="SignatureId">7093</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3196L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"Input"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_BI_IO"</v>
                            </o>
                            <v n="SignatureId">7040</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3197L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bRebuildSegments"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3198L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bAcknowledgeRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3199L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eNodeType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_NodeType.Automatic"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_NodeType"</v>
                            </o>
                            <v n="SignatureId">1406</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3200L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">3802</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3201L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">3802</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3202L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eAssignAsTrendRef"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_AssignRefMode.eInitByProfile"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">18</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_AssignRefMode"</v>
                            </o>
                            <v n="SignatureId">1402</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3203L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDeviceType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="StringType">
                            <n n="SizeExpression" />
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3204L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nInstanceID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3205L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEnPublish"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">3206L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"4, 26, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">1011L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCInputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">793L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">795L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"CLK"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">794L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"Q"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">796L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"R_TRIG"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">791L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"rtrigRstSwi"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">792L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"20, 26, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">784L</v>
                  </o>
                  <o t="CFCOutputElement">
                    <o n="Input" t="CFCInputPinWithSetReset">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="ProcessValue">""</v>
                      <v n="Access" t="ProcessValueAccess">None</v>
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">3230L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bTrigRstSwi"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">3231L</v>
                    </o>
                    <v n="PageArea">4</v>
                    <v n="Bounds">"29, 28, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">3229L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCInputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">3235L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">3236L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"CLK"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">3237L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"Q"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">3238L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"R_TRIG"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">3239L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"rtrigRstButton"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">3240L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"20, 30, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">3234L</v>
                  </o>
                  <o t="CFCOutputElement">
                    <o n="Input" t="CFCInputPinWithSetReset">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="ProcessValue">""</v>
                      <v n="Access" t="ProcessValueAccess">None</v>
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">3246L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bTrigRstButton"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">3247L</v>
                    </o>
                    <v n="PageArea">4</v>
                    <v n="Bounds">"29, 32, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">3245L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">1004L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"TRUE"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">1005L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"21, 41, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">1003L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">3252L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bTrigRstSwi"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">3253L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"3, 45, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">3251L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">3255L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"bTrigRstButton"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">3256L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"3, 46, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">3254L</v>
                  </o>
                  <o t="CFCInputElement">
                    <o n="Output" t="CFCOutputPin">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Negated">false</v>
                      <v n="SetReset" t="SetReset">None</v>
                      <v n="SetResetRef" t="SetResetRef">None</v>
                      <v n="PretendsToBeConnected">false</v>
                      <v n="Id">815L</v>
                    </o>
                    <o n="Text" t="CFCText">
                      <v n="Bounds">"0, 0, 0, 0"</v>
                      <n n="ElementGroupId" />
                      <v n="Text">"T#2s"</v>
                      <v n="Modifiable">true</v>
                      <v n="Id">816L</v>
                    </o>
                    <v n="PageArea">3</v>
                    <v n="Bounds">"13, 48, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">814L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCInputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">804L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">805L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">806L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">""</v>
                          <v n="Modifiable">false</v>
                          <v n="Id">807L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">""</v>
                          <v n="Modifiable">false</v>
                          <v n="Id">808L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">""</v>
                          <v n="Modifiable">false</v>
                          <v n="Id">809L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"OR"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">810L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">""</v>
                          <v n="Modifiable">false</v>
                          <v n="Id">811L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"13, 43, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">Operator</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">803L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCInputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">772L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">774L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">776L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">778L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"IN"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">773L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"PT"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">775L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"Q"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">777L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"ET"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">779L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"TP"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">378L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"tpResetHw"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">379L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" />
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"20, 43, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">371L</v>
                  </o>
                  <o t="CFCBoxElement">
                    <o n="Inputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCInputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">977L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">978L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">979L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">980L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">983L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="IsExtensiblePin">false</v>
                          <v n="ProcessValue">""</v>
                          <v n="Access" t="ProcessValueAccess">None</v>
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">984L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Outputs" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCOutputPin">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">2602L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">2604L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">2606L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">2608L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Negated">false</v>
                          <v n="SetReset" t="SetReset">None</v>
                          <v n="SetResetRef" t="SetResetRef">None</v>
                          <v n="PretendsToBeConnected">false</v>
                          <v n="Id">2610L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Texts" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCText">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bEnSfty"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">988L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bValSfty"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">989L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bEnCrit"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">990L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bValCrit"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">991L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bEnPgm"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">994L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bValPgm"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">995L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bOpState"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">2603L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bActiveEn"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">2605L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"eActivePriority"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">2607L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bActiveVal"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">2609L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"bCmd"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">2611L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"FB_BA_ActuatorCmd"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">999L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Text">"RstHw"</v>
                          <v n="Modifiable">true</v>
                          <v n="Id">1000L</v>
                        </o>
                      </l2>
                    </o>
                    <o n="Parameters" t="CFCItemList">
                      <l2 n="InnerList" cet="CFCParameter">
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"Cmd"</v>
                          <n n="Value" />
                          <v n="InitialValue">"STRUCT(iParent := THIS^, iLabel := LabelFunctions.SwitchingCommand, iProfile := Profiles.BEvt_DisExt_DisturbedNoneNormal_Command, sObjectName := '{Idx=01}', ePolarity := E_BA_Polarity.eNormal, eFeedbackPolarity := E_BA_Polarity.eNormal, eOverriddenPolarity := E_BA_Polarity.eNormal, bEventDetectionEnable := FALSE, eEnPlantLock := E_BA_LockPriority.eNoLock)"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"FB_BA_BO_IO"</v>
                            </o>
                            <v n="SignatureId">6396</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2612L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bRebuildSegments"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2613L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bAcknowledgeRm"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2614L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"eNodeType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"E_BA_NodeType.Automatic"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">13</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"E_BA_NodeType"</v>
                            </o>
                            <v n="SignatureId">1282</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2615L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDescription"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">3832</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2616L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sObjectName"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="UserdefType">
                            <o n="TypeDef" t="VariableExpression">
                              <n n="Type" />
                              <v n="Length" t="Int16">11</v>
                              <v n="VariableId">-1</v>
                              <v n="SignatureId">-1</v>
                              <v n="ScopeId">-1</v>
                              <v n="PositionToSave">-1L</v>
                              <a n="MessagesToSave" et="CompilerMessage" />
                              <v n="Name">"T_MaxString"</v>
                            </o>
                            <v n="SignatureId">3832</v>
                            <v n="ScopeId">-1</v>
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2617L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"sDeviceType"</v>
                          <n n="Value" />
                          <v n="InitialValue">"BA_Globals.sPlaceholder_Empty"</v>
                          <o n="Type" t="StringType">
                            <n n="SizeExpression" />
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2618L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"nInstanceID"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="UDIntType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2619L</v>
                        </o>
                        <o>
                          <v n="Bounds">"0, 0, 0, 0"</v>
                          <n n="ElementGroupId" />
                          <v n="Identifier">"bEnShare"</v>
                          <n n="Value" />
                          <n n="InitialValue" />
                          <o n="Type" t="BoolType">
                            <v n="Compiled">false</v>
                          </o>
                          <v n="Origin" t="ParameterOrigin">Project</v>
                          <v n="Id">2620L</v>
                        </o>
                      </l2>
                    </o>
                    <n n="PreparedParameters" />
                    <v n="PageArea">0</v>
                    <v n="Bounds">"31, 37, 0, 0"</v>
                    <n n="ElementGroupId" />
                    <v n="EnEno">false</v>
                    <v n="KindOfCall" t="KindOfCall">FunctionBlock</v>
                    <v n="ContainsExtensibleInputs">false</v>
                    <v n="Forced">false</v>
                    <v n="OwningPageId">-1L</v>
                    <v n="Id">976L</v>
                  </o>
                </l2>
              </o>
              <o n="ParameterInitializationMethodGenerator" t="CFCParameterInitializationMethodObject">
                <v n="GuidPOU">{7bd49a2c-302a-4348-87f7-45861d4612fa}</v>
                <v n="GuidParentObject">{1161a53a-c10a-4cfa-be73-b8db629377b6}</v>
                <v n="MethodName">"__InitializeParameters_FB_BA_ControlCabinetBasic"</v>
                <v n="ReturnType">"BOOL"</v>
              </o>
              <o n="RoutingPathTable" t="CFCRoutingPathTable">
                <d2 n="InnerDictionary" ckt="CFCRoutingConnection" cvt="CFCPointList">
                  <o>
                    <v n="ConnectionId">3232L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">26</v>
                      <v n="Y">28</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">26</v>
                        <v n="Y">28</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">28</v>
                        <v n="Y">28</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">1007L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">26</v>
                      <v n="Y">45</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">26</v>
                        <v n="Y">45</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">28</v>
                        <v n="Y">45</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">3</v>
                      </o>
                      <o>
                        <v n="X">28</v>
                        <v n="Y">44</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">12</v>
                      </o>
                      <o>
                        <v n="X">30</v>
                        <v n="Y">44</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">695L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">9</v>
                      <v n="Y">22</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">9</v>
                        <v n="Y">22</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">13</v>
                        <v n="Y">22</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">694L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">9</v>
                      <v n="Y">21</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">9</v>
                        <v n="Y">21</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">13</v>
                        <v n="Y">21</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">696L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">12</v>
                      <v n="Y">20</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">12</v>
                        <v n="Y">20</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">13</v>
                        <v n="Y">20</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">3173L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">16</v>
                      <v n="Y">28</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">16</v>
                        <v n="Y">28</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">19</v>
                        <v n="Y">28</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">1678L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">18</v>
                      <v n="Y">20</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">18</v>
                        <v n="Y">20</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">20</v>
                        <v n="Y">20</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">3</v>
                      </o>
                      <o>
                        <v n="X">20</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">12</v>
                      </o>
                      <o>
                        <v n="X">22</v>
                        <v n="Y">18</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">1677L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">18</v>
                      <v n="Y">17</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">18</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">22</v>
                        <v n="Y">17</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">3257L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">10</v>
                      <v n="Y">46</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">10</v>
                        <v n="Y">46</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">12</v>
                        <v n="Y">46</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">3258L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">10</v>
                      <v n="Y">45</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">10</v>
                        <v n="Y">45</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">12</v>
                        <v n="Y">45</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">1006L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">26</v>
                      <v n="Y">41</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">26</v>
                        <v n="Y">41</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">28</v>
                        <v n="Y">41</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">9</v>
                      </o>
                      <o>
                        <v n="X">28</v>
                        <v n="Y">43</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">6</v>
                      </o>
                      <o>
                        <v n="X">30</v>
                        <v n="Y">43</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">3250L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">27</v>
                      <v n="Y">32</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">27</v>
                        <v n="Y">32</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">28</v>
                        <v n="Y">32</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">3248L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">16</v>
                      <v n="Y">29</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">16</v>
                        <v n="Y">29</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">17</v>
                        <v n="Y">29</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">9</v>
                      </o>
                      <o>
                        <v n="X">17</v>
                        <v n="Y">32</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">6</v>
                      </o>
                      <o>
                        <v n="X">19</v>
                        <v n="Y">32</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">813L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">17</v>
                      <v n="Y">45</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">17</v>
                        <v n="Y">45</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">19</v>
                        <v n="Y">45</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                  <o>
                    <v n="ConnectionId">817L</v>
                    <o n="StartPoint" t="CFCPoint">
                      <v n="X">17</v>
                      <v n="Y">48</v>
                      <v n="IsJoint">false</v>
                      <v n="Flags">0</v>
                    </o>
                    <v n="Unroutable">false</v>
                    <n n="CorrespondingPageId" />
                    <v n="Locked">false</v>
                  </o>
                  <o>
                    <l2 n="InnerList" cet="CFCPoint">
                      <o>
                        <v n="X">17</v>
                        <v n="Y">48</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">68</v>
                      </o>
                      <o>
                        <v n="X">18</v>
                        <v n="Y">48</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">3</v>
                      </o>
                      <o>
                        <v n="X">18</v>
                        <v n="Y">46</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">12</v>
                      </o>
                      <o>
                        <v n="X">19</v>
                        <v n="Y">46</v>
                        <v n="IsJoint">false</v>
                        <v n="Flags">97</v>
                      </o>
                    </l2>
                  </o>
                </d2>
              </o>
              <v n="AutoSizeCanvas">true</v>
              <v n="CanvasWidth">45</v>
              <v n="CanvasHeight">51</v>
            </o>
          </Data>
          <TypeList>
            <Type n="Boolean">System.Boolean</Type>
            <Type n="BoolType">{fd373d9e-533d-4d69-ad04-82ccf513ff10}</Type>
            <Type n="CFCBoxElement">{f5becf35-b1f3-4274-b411-81d4b63a1516}</Type>
            <Type n="CFCConnection">{5ae2e111-ecff-4a21-b647-2d4da63f8db7}</Type>
            <Type n="CFCImplementationObject">{32d3375e-c010-41e2-9e43-b2fbf4f2b374}</Type>
            <Type n="CFCInputElement">{d51129f5-df27-4886-99d1-c564d2e2c1f6}</Type>
            <Type n="CFCInputPin">{c994f6e0-311a-4a1c-bc38-75fe34892406}</Type>
            <Type n="CFCInputPinWithSetReset">{5c3476a8-05c5-430e-861c-9cfa51d68ca8}</Type>
            <Type n="CFCItemList">{cd57ba20-558b-4b98-96c1-73c6000c3087}</Type>
            <Type n="CFCOutputElement">{8d9e2b78-3efe-4fe4-8160-f3a7381ddd8f}</Type>
            <Type n="CFCOutputPin">{65582d84-cf18-4ca0-be59-bf5a3d00b8f8}</Type>
            <Type n="CFCParameter">{16471219-97ce-4580-8682-e60492a6d970}</Type>
            <Type n="CFCParameterInitializationMethodObject">{f13d20a6-591c-4ca8-9a3d-8574380b6bcc}</Type>
            <Type n="CFCPoint">{b3e42b54-b8f2-45d3-825d-747f82f244a0}</Type>
            <Type n="CFCPointList">{584effbc-813e-443a-bf78-ad9c8d49db41}</Type>
            <Type n="CFCRoutingConnection">{93c117eb-0884-403b-b01e-28b89f47e041}</Type>
            <Type n="CFCRoutingPathTable">{4b8bcc79-5980-4868-b49e-005a8148859b}</Type>
            <Type n="CFCText">{72f2b13f-5349-4a8a-bbe6-2bccf3f42179}</Type>
            <Type n="CompilerMessage">{bc2be951-49f6-4f0f-b731-e31e36606f1e}</Type>
            <Type n="Guid">System.Guid</Type>
            <Type n="Int16">System.Int16</Type>
            <Type n="Int32">System.Int32</Type>
            <Type n="Int64">System.Int64</Type>
            <Type n="KindOfCall">{77f43dfe-ca6a-4869-828f-7609d8ed6ea6}</Type>
            <Type n="ParameterOrigin">{00f7522c-f616-4f07-a530-7175f7cba90b}</Type>
            <Type n="ProcessValueAccess">{88453c7d-d652-4a27-a1b0-a1953be49a5c}</Type>
            <Type n="SetReset">{24449d48-c96a-49c4-b9d1-a4ea34aedce3}</Type>
            <Type n="SetResetRef">{233bc97c-69fe-4d29-b40e-a9a9b854044e}</Type>
            <Type n="String">System.String</Type>
            <Type n="StringType">{ab09737e-b891-4fc6-9c8c-246eb8cdb046}</Type>
            <Type n="UDIntType">{223d196a-c1d7-4283-aea6-270599207584}</Type>
            <Type n="UserdefType">{8499b87a-2b75-4c62-8657-e4aa9316c18b}</Type>
            <Type n="VariableExpression">{6708bd14-cddc-4e28-b69d-d3183b7c423e}</Type>
          </TypeList>
        </XmlArchive>
      </CFC>
    </Implementation>
    <Folder Name="[Private]" Id="{024b046a-664d-49d2-bb07-97be0eadde0d}" />
    <Folder Name="[Protected] Management" Id="{85912088-ad90-47de-97a7-570e488812bc}" />
    <Method Name="Ack" Id="{af109ea4-070e-4e58-b5ce-40236a2c408d}" FolderPath="[Private]\">
      <Declaration><![CDATA[METHOD PRIVATE Ack
VAR_INPUT
	iView			: I_BA_View;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (iView <> 0) THEN
	iView.AcknowledgeObjectsPLC := (bTrigRstSwi) OR (bTrigRstButton);	
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="EventEvaluation" Id="{a7916a83-24ce-43a5-9205-f7f86645c89c}" FolderPath="[Private]\">
      <Declaration><![CDATA[METHOD PRIVATE EventEvaluation
VAR
	_iView			: I_BA_View;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[bIsDisturbed := FALSE;
bHasUnackEvent := FALSE;

IF (iAckView1 = 0) AND (iAckView2 = 0) AND (iAckView3 = 0) THEN
	// Treat project structure via root-object:
	Ack(BA_Globals.Top);
	GetErrors(BA_Globals.Top);
ELSE
	// Treat each defined object:
	Ack(iAckView1);
	GetErrors(iAckView1);
	
	Ack(iAckView2);
	GetErrors(iAckView2);
	
	Ack(iAckView3);
	GetErrors(iAckView3);
END_IF

// Generate alarm lamp impulse:
tAlmLampImpuls();

bBlink := tAlmLampImpuls.bQ;]]></ST>
      </Implementation>
    </Method>
    <Method Name="FB_init" Id="{12d1fc59-1c6e-471b-895f-17582d0de6f1}">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[LampFault.iParent							:= THIS^;
LampFault.iLabel							:= LblCmpGeneral.ControlCabinet_LampFault;			
LampFault.sObjectName						:= '{Idx=01}';
LampFault.eDPADMode							:= E_BA_DPADMode.eInclude;																						
LampFault.Cmd.iLabel						:= LblCmpGeneral.ControlCabinet_LampFault_Cmd;			
LampFault.Cmd.sObjectName					:= '{Idx=01}';	
LampFault.Cmd.ePolarity						:= E_BA_Polarity.eNormal;
LampFault.Cmd.eFeedbackPolarity				:= E_BA_Polarity.eNormal;
LampFault.Cmd.eOverriddenPolarity			:= E_BA_Polarity.eReverse;
LampFault.Cmd.sActiveText 					:= Texts.txtOn;
LampFault.Cmd.sInactiveText 				:= Texts.txtOff;
LampFault.Cmd.nEventClassID					:= EventClasses.DisturbanceExtended;
LampFault.Cmd.aEventTransitionText[1]		:= Texts.txtDisturb;
LampFault.Cmd.aEventTransitionText[2]		:= Texts.txtNone;
LampFault.Cmd.aEventTransitionText[3]		:= Texts.txtNormal;
LampFault.Cmd.bEventDetectionEnable			:= TRUE;
LampFault.Cmd.eEnPlantLock					:= E_BA_LockPriority.eNoLock;	

AckButton.iParent							:= THIS^;		
AckButton.iLabel 							:= LblCmpGeneral.ControlCabinet_AckButton;	
AckButton.sObjectName						:= '{Idx=01}';
AckButton.eDPADMode							:= E_BA_DPADMode.eInclude;																						
AckButton.Input.iLabel						:= LblCmpGeneral.ControlCabinet_AckButton_Input;
AckButton.Input.ePolarity					:= E_BA_Polarity.eNormal;
AckButton.Value.iLabel						:= LblCmpGeneral.ControlCabinet_AckButton_Value;
AckButton.Value.eToggleMode 				:= E_BA_ToggleMode.ePushButton;									

RstHw.iParent								:= THIS^;
RstHw.iLabel								:= LblCmpGeneral.ControlCabinet_RstHw;			
RstHw.sObjectName							:= '{Idx=02}';
RstHw.eDPADMode								:= E_BA_DPADMode.eInclude;																						
RstHw.Cmd.iLabel							:= LblCmpGeneral.ControlCabinet_RstHw_Cmd;			
RstHw.Cmd.sObjectName						:= '{Idx=01}';	
RstHw.Cmd.ePolarity							:= E_BA_Polarity.eNormal;
RstHw.Cmd.eFeedbackPolarity					:= E_BA_Polarity.eNormal;
RstHw.Cmd.eOverriddenPolarity				:= E_BA_Polarity.eReverse;
RstHw.Cmd.sActiveText 						:= Texts.txtOn;
RstHw.Cmd.sInactiveText 					:= Texts.txtOff;
RstHw.Cmd.nEventClassID						:= EventClasses.DisturbanceExtended;
RstHw.Cmd.aEventTransitionText[1]			:= Texts.txtDisturb;
RstHw.Cmd.aEventTransitionText[2]			:= Texts.txtNone;
RstHw.Cmd.aEventTransitionText[3]			:= Texts.txtNormal;
RstHw.Cmd.bEventDetectionEnable				:= TRUE;
RstHw.Cmd.eEnPlantLock						:= E_BA_LockPriority.eNoLock;	

tAlmLampImpuls.bEn							:=	TRUE; 
tAlmLampImpuls.nTiOn						:=	800;
tAlmLampImpuls.nTiOff						:=	800;]]></ST>
      </Implementation>
    </Method>
    <Method Name="GetErrors" Id="{7d4cdfdd-7941-4230-96bd-fd54056feeea}" FolderPath="[Private]\">
      <Declaration><![CDATA[METHOD PRIVATE GetErrors
VAR_INPUT
	iView			: I_BA_View;
END_VAR
VAR
	iTemp			: INT;
	fbEvents		: REFERENCE TO FB_BA_EventIndicator;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[IF (iView <> 0) THEN
	fbEvents REF= iView.ActiveEvents;
	
	FOR iTemp := E_BA_EventType.First TO E_BA_EventType.Last DO
		IF (fbEvents.aEventsPerIconImage[iTemp].nCount > 0) THEN
			bIsDisturbed := TRUE;
			
			CASE (fbEvents.aEventsPerIconImage[iTemp].eMostPriorisedState) OF
				E_BA_EventIconState.ePresent,
				E_BA_EventIconState.eGone:
					bHasUnackEvent := TRUE;
			END_CASE
		END_IF
	END_FOR
END_IF]]></ST>
      </Implementation>
    </Method>
    <Method Name="Reset" Id="{4b7e996f-2b2c-4a34-8b96-5546044e48cc}" FolderPath="[Protected] Management\">
      <Declaration><![CDATA[METHOD PROTECTED Reset
VAR_INPUT
	bUnregister			: BOOL			:= FALSE;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[iAckView1 := 0;
iAckView2 := 0;
iAckView3 := 0;

SUPER^.Reset(bUnregister);]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_BA_ControlCabinetBasic.Ack">
      <LineId Id="13" Count="0" />
      <LineId Id="30" Count="0" />
      <LineId Id="20" Count="0" />
    </LineIds>
    <LineIds Name="FB_BA_ControlCabinetBasic.EventEvaluation">
      <LineId Id="6" Count="2" />
      <LineId Id="37" Count="0" />
      <LineId Id="10" Count="17" />
      <LineId Id="29" Count="0" />
    </LineIds>
    <LineIds Name="FB_BA_ControlCabinetBasic.FB_init">
      <LineId Id="9" Count="2" />
      <LineId Id="138" Count="0" />
      <LineId Id="119" Count="12" />
      <LineId Id="23" Count="0" />
      <LineId Id="25" Count="2" />
      <LineId Id="139" Count="0" />
      <LineId Id="85" Count="0" />
      <LineId Id="91" Count="0" />
      <LineId Id="84" Count="0" />
      <LineId Id="78" Count="0" />
      <LineId Id="49" Count="3" />
      <LineId Id="141" Count="0" />
      <LineId Id="105" Count="11" />
      <LineId Id="101" Count="0" />
      <LineId Id="68" Count="3" />
    </LineIds>
    <LineIds Name="FB_BA_ControlCabinetBasic.GetErrors">
      <LineId Id="35" Count="0" />
      <LineId Id="50" Count="0" />
      <LineId Id="80" Count="0" />
      <LineId Id="55" Count="0" />
      <LineId Id="58" Count="0" />
      <LineId Id="63" Count="0" />
      <LineId Id="65" Count="0" />
      <LineId Id="67" Count="0" />
      <LineId Id="70" Count="2" />
      <LineId Id="69" Count="0" />
      <LineId Id="62" Count="0" />
      <LineId Id="45" Count="0" />
      <LineId Id="29" Count="0" />
    </LineIds>
    <LineIds Name="FB_BA_ControlCabinetBasic.Reset">
      <LineId Id="124" Count="2" />
      <LineId Id="80" Count="0" />
      <LineId Id="60" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>